name: Default workflows
on:
  push:
    branches:
      - "main"
      - "release*"
  pull_request:

jobs:
  golangci-lint:
    runs-on: ["self-hosted"]
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' || startsWith(github.ref, 'refs/heads/release')
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.3
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: --timeout=5m
          skip-pkg-cache: true
          skip-build-cache: true
